sudo: enabled
dist: trusty
language: ruby
rvm:
 - 2.3
cache: bundler
script:
  - |
    rc=0;
    for sha1 in $(git log --format=format:%H ${TRAVIS_COMMIT_RANGE}); do
      echo $sha1;
      git log --format=%B -n 1 $sha1;
      bundle exec rubocop-git "${sha1}~1";
      if (( $? != 0 )); then rc=1; fi;
      echo -e "\n\n\n";
    done;
    exit $rc;
